// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2YHM3sYEho1VykYkVRe3jzvY3bckZ6GQ',
    appId: '1:62117856035:web:818f86462b552de45b4296',
    messagingSenderId: '62117856035',
    projectId: 'flutter-auth-app-43945',
    authDomain: 'flutter-auth-app-43945.firebaseapp.com',
    storageBucket: 'flutter-auth-app-43945.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACDmXjDfYpxXomAdbfjJHl5c-AoU3FMU',
    appId: '1:62117856035:android:5b265298f87a89775b4296',
    messagingSenderId: '62117856035',
    projectId: 'flutter-auth-app-43945',
    storageBucket: 'flutter-auth-app-43945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1GE3pp7xE3WgLoW2sxJCPq4mYGLhWkjE',
    appId: '1:62117856035:ios:10492de4246297bc5b4296',
    messagingSenderId: '62117856035',
    projectId: 'flutter-auth-app-43945',
    storageBucket: 'flutter-auth-app-43945.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthApp',
  );
}
